#!/usr/bin/env ruby
taza_dev = 'c:/work/taza/'

$LOAD_PATH.unshift taza_dev + 'lib'
APP_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))

begin
  require 'rubigen'
rescue LoadError
  require 'rubygems'
  require 'rubigen'
end
require 'rubigen/scripts/generate'

ARGV.shift if ['--help', '-h'].include?(ARGV[0])
RubiGen::Base.use_component_sources! [:taza, :test_unit]
RubiGen::Base.prepend_sources(RubiGen::PathSource.new(:dev, taza_dev + 'generators'))
RubiGen::Scripts::Generate.new.run(ARGV)
