#!/usr/bin/env ruby
$LOAD_PATH.unshift ENV['TAZA_DEV'] + 'lib' if ENV['TAZA_DEV']
APP_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))

begin
  require 'rubigen'
rescue LoadError
  require 'rubygems'
  require 'rubigen'
end
require 'rubigen/scripts/generate'

ARGV.shift if ['--help', '-h'].include?(ARGV[0])
RubiGen::Base.use_component_sources! [:taza, :test_unit]
if ENV['TAZA_DEV']
  RubiGen::Base.prepend_sources(
    RubiGen::PathSource.new(:dev, ENV['TAZA_DEV'] + 'generators'))
end
RubiGen::Scripts::Generate.new.run(ARGV)
