#!/usr/bin/env ruby
APP_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))

begin
  require 'rubigen'
rescue LoadError
  require 'rubygems'
  require 'rubigen'
end
require 'rubigen/scripts/generate'

ARGV.shift if ['--help', '-h'].include?(ARGV[0])
RubiGen::Base.use_component_sources! [:watircraft, :test_unit]
if ENV['WATIRCRAFT_DEV']
  $LOAD_PATH.unshift File.join(ENV['WATIRCRAFT_DEV'], 'lib')
  dev_generators = File.join(ENV['WATIRCRAFT_DEV'], 'watircraft_generators')
  RubiGen::Base.prepend_sources(RubiGen::PathSource.new(:dev, dev_generators))
end
RubiGen::Scripts::Generate.new.run(ARGV)
